### PR TITLE
Support default Django required field handling - issue #132

### PR DESCRIPTION
**Pull request by AimeeMS**

### CODE REVIEW

**Comment by dominicrodger** [comment]
Looks like this failed tests - could you try to fix the tests and update the pull request?

**Comment by AimeeMS** [comment]
I have pushed an update to address all but test_dt_start_and_dtend_converts_to_utc (line 57 in test_tz.py).

I am not familiar with this use case and am having some issues replicating this test with the RecurrenceField.

**Comment by AimeeMS** [comment]
@dominicrodger I see that the previous test (test_strip_dtstart_and_dtend_if_required) has a recurrence rule applied.
Perhaps the next test (the one that my update is failing on) is supposed to have a rule applied as well. What are your thoughts?

**Comment by dominicrodger** [comment]
@AimeeMS - good spot. I think either we need to add a rule to it, or perhaps we can mark the field as not required on line 56?

**Comment by dominicrodger** [comment]
Looks good - I'll merge and add docs tonight, all going well.

**Comment by AimeeMS** [comment]
Thank you.
I am wondering when you think I may be able to pull this update (and some other recent, helpful updates - such as issue #128 ) in from the pip package?

**Comment by dominicrodger** [comment]
Good question, and whoops, #128 isn't in the release notes. We've got quite a few bits in 1.8.0 now, so once I've updated docs, I'll ask @emperorcezar to push a release to PyPI.

**Comment by AimeeMS** [comment]
That sounds great. Thank you.

**Comment by dominicrodger** [comment]
Turns out #128 was in the release notes, since it was fixed in #131. I've pushed documentation updates.

Also, I just tried pushing a release to PyPI, and it turns out I can. Enjoy :)

**Comment by AimeeMS** [comment]
Thanks

**Pull request merged**
