### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by josesanch**
Could you please merge the spanish translation of the app?

Thanks

### CODE REVIEW

**Comment by dominicrodger** [comment]
Great - thanks for this - I'll add notes to the changelog, and hopefully @emperorcezar can cut a release with this in for you.

**Comment by dominicrodger** [comment]
@emperorcezar - any chance you can push 1.2.0 to PyPI? There's quite a bit in 1.2.0 now, so it'd be good to get it out there (http://django-recurrence.readthedocs.org/en/latest/changelog.html#as-yet-unreleased.

**Comment by emperorcezar** [comment]
Just pushed the latest version.

**Comment by dominicrodger** [comment]
Awesome - thanks @emperorcezar :)

**Pull request merged**
