### PR TITLE
Add German translation

### PR DESCRIPTION
**Pull request by denisiko**
Including new date formats like dd.mm.YYYY and 23. for 23th etc.

Changes:
* Adding translation strings in recurrence.js (day of month & date format for "until ...")
* Creating new po/mo files (Dutch/French translations from @bheesink and @ollb were quite helpful as basis for translation)

Further contributions and improvements are always welcome. Keep up the nice work!

### CODE REVIEW

**Comment by denisiko** [comment]
Hope the project is not dead, I would really appreciate some feedback.

**Comment by dominicrodger** [comment]
Definitely not dead, sorry for the slow reply. I'll aim to take a look at
this today.

**Comment by denisiko** [comment]
Glad to hear that!

**Comment by dominicrodger** [comment]
Thanks @denisiko! The change looks good, so I've merged it. I'll wait a bit to see if any other pull requests come in over the next few weeks - if not, I'll get a release merged with it.

**Comment by denisiko** [comment]
Nice! Hope someone can use it.

**Comment by dominicrodger** [comment]
I checked, and we have a few things in 1.4.1 already, so hopefully @emperorcezar can push a release fairly soon (Adam - if it's easier feel free to just grant me access to PyPI so I can do it).

**Pull request merged**
