### PR TITLE
allow negative bymonthday

### PR DESCRIPTION
**Pull request by mir06**
Following the work of @bartekbrak in pull-request #59 I implemented the possibility to use negative values for the monthly rules, i.e. count days from the end of the month.  

The widget uses the four remaining cells to allow entering of the last, second, third and fourth but last day. I suppose there are very few scenarios where more is needed.  
 
Translations are provided for all previous languages except basque.

@dominicrodger: by the way this is a very great django-app :+1:

### CODE REVIEW

**Comment by dominicrodger** [comment]
This LGTM - thanks for all the work here @mir06! :+1:

I've not got a great deal of experience with translations - do you know what the implications of the missing Basque changes are? What difference will that make?

Any thoughts here @emperorcezar or @tamask? If there are no objections in the next week or so I'll get this merged.

Also - all the credit for django-recurrence is for @tamask who wrote it originally, and @emperorcezar who got it up on PyPI :)

**Comment by mir06** [comment]
@dominicrodger it's just about 7 strings that have to be translated (last, second last, 2nd last, third last, 3rd last, fourth last and 4th last). probably @unaizalakain could do this.

**Comment by dominicrodger** [comment]
Great - thanks @mir06. I've just got this merged, I'll add some release notes shortly, and file an issue for getting those 7 string added to the Basque translation. Thanks again for all your work on this - particularly for getting all those strings translated.

**Comment by mir06** [comment]
@dominicrodger thank you :+1:

**Comment by emperorcezar** [comment]
@dominicrodger Let me know if/when you want to cut a release. Also, could you make an issue to cut a release and assign it to me? Make it easier to track.

**Comment by dominicrodger** [comment]
Will do, thanks @emperorcezar - there are a few more things that I'd like to get in before we get a release out (mostly #87 and #92).

**Pull request merged**
