### PR TITLE
Support Django 2.0

### PR DESCRIPTION
**Pull request by erikriver**

### CODE REVIEW

**Comment by noamkush** [comment]
You should use cascade, otherwise this will be incompatible with the database state for deployments that had already applied the migrations.

**Comment by dominicrodger** [comment]
Hi @erikriver,

Thanks for taking a look at this! Is there a reason why you modified the existing migration instead of creating a 0002 file?

Dom

**Comment by noamkush** [comment]
There's no need for a new migration since there's no need to touch the database. On the other hand, you need to use `CASCADE`, which is the old default, and not `DO_NOTHING`.

**Comment by kedlav** [comment]
I opened #110, which provides better defaults, includes tests of django2, and updates docs.

**Comment by dominicrodger** [comment]
Closing this in favour of #110 (which is now merged). Thanks for the work here though @erikriver, it's much appreciated.

**Pull request closed without merging**
