### PR TITLE
Fix incorrect month name for May in widget

### PR DESCRIPTION
**Pull request by randlet**
The month name for May in the widget was showing as "month name". This patch fixes that.

### CODE REVIEW

**Comment by dominicrodger** [comment]
Which translation were you using? Honestly, I'm not entirely sure why that code is there, but I'm pretty certain it's there for a reason.

**Comment by randlet** [comment]
Just using English, but notice how only May used pgettext and the rest of the months use gettext.  This results in a widget like this:

image

All I've done is switch the translation request for May to be consistent with the other months.

**Comment by randlet** [comment]
Nevermind...I see that pgettext is used to disambiguate the month May from other usages of 'may'. Sorry about that!

**Comment by dominicrodger** [comment]
Ah, nice - what did you do to get the widget to show up correctly? Anything we're missing in docs?

**Comment by randlet** [comment]
Was not a problem with django-recurrence...PEBCAK.  I forgot I had overwritten pggettext in my own code while debugging another issue. Sorry to add some unneeded noise!

**Comment by dominicrodger** [comment]
No worries - glad you worked it out!

**Pull request closed without merging**
