### PR TITLE
date Python and Django versions and CI setup

### PR DESCRIPTION
**Pull request by aleksihakli**
Some of the stylistic code updates in this PR are not intended as-is and they are still WIP and subject to cleanup.

### CODE REVIEW

**Comment by aleksihakli** [comment]
Hey @dominicrodger! I made updates for upgrading the test setup and compatibility for newer Python and Django versions as well as running tests with GitLab Actions, but the tests won't run, probably because they are not enabled yet? Would it be possible to enable them via the Actions UI?

https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow#enabling-a-workflow

**Comment by aleksihakli** [comment]
It seems that Python 3.7 - 3.10 all work for Django versions up to version 4.0 which has deprecated the use of `pytz` in favor of the standard library `zoneinfo` package:

- https://docs.djangoproject.com/en/4.0/releases/4.0/#zoneinfo-default-timezone-implementation
- https://docs.python.org/3/library/zoneinfo.html#module-zoneinfo

The code will require updates in order to handle `.localize()` correctly or deprecate them.

**Comment by dominicrodger** [comment]
Hi @aleksihakli - thanks for all this! Sorry, I've never used GitHub actions before - I see you've added a filed called `.github/dependabot.yml` - which type of action do I need to enable for that? I tried a couple, but they seemed to just want me to create config files. Perhaps I need to merge this PR first?

**Comment by aleksihakli** [comment]
Hey @dominicrodger, seems like the actions might require upstreaming in order to run properly.

I'm still validating all the CI and test flows with the updates but you can see the progress here: https://github.com/aleksihakli/django-recurrence/actions

I'll ping you back once the PR passes the test suite with GitHub actions and is a viable candidate for review and merging.

**Comment by aleksihakli** [comment]
The PR is now ready for review and merging if you think it looks OK @dominicrodger.

I've added support for newer Python 3 versions as well as added PyPy 3.8 to the test matrix since it's a good validator for cross-implementation compatibility.

I've mainly updated the project infrastructure settings, moved from Travis to GitHub Actions, and removed some legacy Python 2 code that would prevent newer Django version compatibility, there should be no code logic changes at all in this PR.

Django 4.0 and development main branch support is still pending because the source code needs updates to deprecate the use of `pytz` `localize()` method usage, but I think that would ideally be solved by another PR as it would change actual code logic?

**Comment by dominicrodger** [comment]
Great - merged - what do I need to do next here for GitHub Actions?

**Comment by aleksihakli** [comment]
It seems like the Actions based builds are now properly rolling and working so that should be OK :) They seem to have started functioning with the merge.

Next thing to do would be to probably fix the docs build (seems to be failing for some reason), update the Django 4.0 support and possibly add an automated release pipeline?

I am mostly familiar with the Jazzband release automation and was thinking that I could first try to upgrade the source code for Django 4.0 support, and then open a proposal for the project and PyPI release automation via the Jazzband org if that's OK with you?

**Comment by dominicrodger** [comment]
That all sounds good to me - thank you so much!

**Pull request merged**
