### PR TITLE
Fixes #87

### LINKED ISSUE #87: "Add Rule" "Add Date" buttons inoperative in Admin Inline.
django=1.9.12
django-recurrence=1.4.1

When using recurrence in django admin, if recurrence is a field on an inline model and an instance of the inline model is spawned using the "Add whatever" button then the "Add Rule" and "Add Date" buttons in recurrence do not function. The recurrence widget functions normally if the inline object is visible when loading the page.

### PR DESCRIPTION
**Pull request by pasevin**
This is my attempt at fixing this long-standing issue. It works for my needs without issues so far.
I've utilized MutationObserver for observing DOM node additions. And replaced Django render method with a javascript initialization instead.

### CODE REVIEW

**Comment by dominicrodger** [comment]
This looks good to me - just two comments:

1. Can you remove the imports of safestring, get_language and simplejson as json, since they're no longer used? (That'll fix the flake8 checks)
2. My JavaScript knowledge isn't good enough to know what browsers this will work in - do you know? From a quick glance, I think [MutationObserver](https://www.caniuse.com/#feat=mutationobserver) is the main thing here, but that looks to be fairly widely supported. Anything else I'm missing?

Thanks for your efforts on this - they're much appreciated!

**Comment by pasevin** [comment]
Cool!
1. Done.
2. I went with MutationObserver vs DOMNodeInserted, which is used more widely and easier to implement, but looking forward is deprecated. I think this is the only reasonable way to go.

**Comment by dominicrodger** [comment]
Fantastic - thanks @pasevin! All going well I'll test this and merge it tonight.

**Comment by dominicrodger** [comment]
Hi @pasevin - I can't get this to work locally - `targetNode` on line 7 of recurrent-widget.init.js is always null. Where does the class `grp-content-container` come from? I can't see it anywhere in Django's source. I've tested Django 2.1.7 and 1.11.14. Any ideas?

**Comment by pasevin** [comment]
My bad! It's a native django-grappelli class name. I will fix it asap. I knew I will screw this up in some wayt :))

**Comment by pasevin** [comment]
Should be working now.

**Comment by dominicrodger** [comment]
Awesome - thanks @pasevin. I'll take another look as soon as I can (hopefully by the end of the week).

**Comment by skumarcm** [comment]
I am trying to use this package for my recurrence.
I am getting the following error:

recurrence-widget.init.js:7 Uncaught TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at HTMLDocument.<anonymous> (recurrence-widget.init.js:7)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at Function.ready (jquery.min.js:2)
    at HTMLDocument.J (jquery.min.js:2)

The node with the id "container" is no where to find.
Where exactly is the above node?

**Comment by amirfuhrmann** [comment]
i get the same
recurrence version 1.10.2/django 2.2.2/python3.7.7
any thoughts ?

**Pull request merged**
