### PR TITLE
Fix for including/excluding dates in occurrences when dtstart is given

### PR DESCRIPTION
**Pull request by douwevandermeij**
Little bit more logic for including dates in rruleset.
Our occurrences list was not correct so we changed it into this.

### CODE REVIEW

**Comment by douwevandermeij** [comment]
It was a while ago when we changed the code and we didn't fix unit tests. I'll check them.

**Comment by douwevandermeij** [comment]
line 184 in test_occurrences is solved by this:
# We always get dtend, for reasons that aren't entirely clear
datetime(2014, 1, 5, 0, 0, 0),

**Comment by douwevandermeij** [comment]
also line 49 in test_saving:

datetime(2014, 2, 3, 0, 0)  # We always get dtend

**Comment by douwevandermeij** [comment]
This should be right.
dtstart and dtend should be part of the occurrences, so not included always.
See added unit test for an example.

**Comment by douwevandermeij** [comment]
This also solves the problem we encountered having the same date twice in occurrences, if I recall correctly.

**Comment by dominicrodger** [comment]
Hi @douwevandermeij,

I'm not sure what to do about this. On the one hand, the current behaviour is pretty odd (as evidenced by the comments you discovered in the tests which I wrote to try to nail down what this function is meant to do). On the other, your changes change some behaviour which I think is intentional (e.g. that `dtstart` is always included - or was that what you were referring to when you mentioned duplicate dates?). I think before this gets merged, we'll need to narrow down exactly what we're changing, and why, and document that clearly in the release notes (I'm happy to do some documentation work if it'd help).

Thanks for taking a look at this - I really appreciate it!

Dom

p.s. It took me a bunch of retries (pip/Travis being flaky - nothing you've done wrong), but this now passes the Travis build.

**Comment by douwevandermeij** [comment]
I agree that this merge might result in not being backwards compatible. On the other hand, I think people that will have a backwards compatibility issue are having an incorrect application at the moment.
The Travis errors were strange indeed, I noticed. Thanks for fixing them :)
We started looking at this issue when we noticed incorrect occurrences when having a weekly rule on a day that is not the same as the day of `dtstart` nor `dtend`.

See `test_occurrences_with_start_and_end_weekly_tuesdays`, the current implementation gives these occurences (having `dtstart` and `dtend` on a thursday):
`[datetime.datetime(2015, 1, 1, 0, 0), datetime.datetime(2015, 1, 6, 0, 0), datetime.datetime(2015, 1, 8, 0, 0)]`, notice `dtstart` and `dtend` being in the list, while this should be:
`[datetime.datetime(2015, 1, 6, 0, 0)]`, the only true tuesday occurrence that week.

I can't reproduce having double occurrences in the list. Maybe some other commit I merged with already fixed that.

**Comment by ezheidtmann** [comment]
This PR seems to fix #50 for me. I have a workaround for this bug in my use case, but would love to see this merged ASAP. What can I do to help?

**Comment by andybak** [comment]
Just a friendly bump. The behaviour fixed by https://github.com/django-recurrence/django-recurrence/pull/36/commits/94e8e785e77a9ebf996dafee548f5afc9cb29329 is especially strange and confusing. It would be great to see that merged.

**Comment by denisiko** [comment]
Would also love to see this merged as it affects at least 3 issues.

**Comment by emperorcezar** [comment]
@douwevandermeij You mention in #90 that we should be following the spec. I agree. In that vain, should this stay open? I'm in favor of closing this and applying work to #93

**Comment by douwevandermeij** [comment]
@emperorcezar I agree to close this PR.

**Comment by andybak** [comment]
Fair enough. A plague on RFC 2445 however and whatever demented reasoning made sense to the authors at the time.

**Pull request closed without merging**
