### PR TITLE
Fix Issue #62. SubfieldBase has been deprecated in Django 1.9

### PR DESCRIPTION
**Pull request by edelvalle**
Warning: RemovedInDjango110Warning: SubfieldBase has been deprecated in Django 1.9

### CODE REVIEW

**Comment by emperorcezar** [comment]
:+1: Looks good to me if tests pass

**Comment by dominicrodger** [comment]
Thanks for looking at this @edelvalle. It's worth noting that we don't currently test against Django 1.8, so it might be worth adding that first, to make sure we support both 1.7 and 1.8 (since those are the versions we're switching on).

**Comment by edelvalle** [comment]
How do I do that? modifying the tox file?

**Comment by dominicrodger** [comment]
If you modify `envlist` in the tox.ini file, it should test against all the supported Python/Django versions (and combinations thereof) when you run `tox`.

I've filed #64 to get that done - I suspect we won't be able to add tests for Django 1.8/1.9 until this change gets merged, so in #64 I'll just work on reducing the combinations of things we test (there's no point testing on Django/Python versions that are EOL).

**Comment by dominicrodger** [comment]
This definitely breaks tests for Django 1.8 (I just added those tests in ff64fb8). Are you happy to take another look at this @edelvalle? If not, I'll see if I can figure out what's wrong here.

These tests fail with 1.8:

> 
> __________________________________________________________________________ test_recurrence_text_pattern_is_saved __________________________________________________________________________
> tests/test_saving.py:14: in test_recurrence_text_pattern_is_saved
>     assert len(event.recurs.rrules) == 1
> E   AttributeError: 'str' object has no attribute 'rrules'
> _____________________________________________________________________________ test_recurrence_object_is_saved _____________________________________________________________________________
> tests/test_saving.py:54: in test_recurrence_object_is_saved
>     assert event.recurs == limits
> E   assert 'DTSTART:20140101T000000Z\nDTEND:20140203T000000Z\nRRULE:FREQ=WEEKLY' == <recurrence.base.Recurrence object at 0x7fc34d6b9048>
> E    +  where 'DTSTART:20140101T000000Z\nDTEND:20140203T000000Z\nRRULE:FREQ=WEEKLY' = <EventWithNoNulls: EventWithNoNulls object>.recurs
>

**Comment by edelvalle** [comment]
Gentelmen, Here I'm again adding support for django 1.8 and 1.9 with no warnings. :smile:

**Comment by dominicrodger** [comment]
Great work - thanks @edelvalle! I'll look to add notes to our changelog/docs and then I'll get this merged. @emperorcezar - we'll probably want to push a new version to PyPI once this change is in, so @edelvalle can use his work without needing a local version.

**Comment by edelvalle** [comment]
@dominicrodger btw, I tested this also in Python 3.5, tox does not support it now.. but I hacked it :smile:. So as soon as it supports it, it can be added to the tox file.

**Comment by dominicrodger** [comment]
Cool - thanks! Really appreciate the extra work you've done here.

**Pull request merged**
