### PR TITLE
Add basque translations

### PR DESCRIPTION
**Pull request by unaizalakain**

### CODE REVIEW

**Comment by dominicrodger** [comment]
Looks good - thanks for doing this @unaizalakain! I'll aim to get this merged in the next day or two, unless someone else gets there first.

**Comment by unaizalakain** [comment]
Is there a chance of getting this merged in the near future? Cheers!

**Comment by dominicrodger** [comment]
Merged - I'll update the changelog, bump the version and then hopefully @emperorcezar can get a new release onto PyPI so you can use your work. Sorry for the delay.

**Comment by dominicrodger** [comment]
OK - I've updated the [changelog](http://django-recurrence.readthedocs.io/en/latest/changelog.html). @emperorcezar - can you push a new release to PyPI when you get a moment?

**Comment by unaizalakain** [comment]
Thank you so much!

**Pull request merged**
