### PR TITLE
Add attribute check in check_urlpatterns

### PR DESCRIPTION
**Pull request by AimeeMS**
In addition to #131, I believe we also will need to apply the attribute check in the check_urlpatterns function.

### CODE REVIEW

**Comment by dominicrodger** [comment]
Looks fine to me, merged. I'll push 1.8.1 once I've given a bit of time for any other issues to be reported (perhaps at the end of the week).

@AimeeMS - are you interested in helping maintain django-recurrence? I'm no longer using it in any of my projects, so I'm looking for other people to help out.

**Comment by AimeeMS** [comment]
That sounds great. I look forward to it.

I would be interested in helping out when I have free time, yes.

**Comment by dominicrodger** [comment]
Great - I've pushed 1.8.1, and invited you to join the django-recurrence team. Thanks @AimeeMS!

**Comment by AimeeMS** [comment]
@dominicrodger, thanks for pushing this out.
Oddly, I am not seeing recent updates in the source for 1.8.1.

**Comment by dominicrodger** [comment]
Whoops, my bad. I've just pushed 1.8.2, and update the docs. Could you try that for me?

**Comment by AimeeMS** [comment]
Yep. I can confirm that the updates are in 1.8.2.

**Pull request merged**
